# deployment configuration for fayolle
# https://docs.ionos.space/docs/deployment-configuration/

distFolder: dist

bootstrap:
  excludes:
    - .git
    - .github
    - .deploy-now

recurring:
  excludes:
    - .git
    - .github
    - .deploy-now
